### ISSUE TITLE
Cannot read properties of undefined (reading 'onMessage')

### ISSUE THREAD

**Issue by kyletaylored** [davestewart/extension-bus#11]
I've been reading through the README, but wasn't sure if this is something covered. I've been trying different methods of creating a communication channel from a popup to a content script in the [MAIN world context](https://developer.chrome.com/docs/extensions/reference/api/scripting#type-ExecutionWorld) to display data in the popup from the `window` object, but you lose access to `chrome.runtime` APIs which throws the error:

```
index.mjs:183 Uncaught TypeError: Cannot read properties of undefined (reading 'onMessage')
    at makeBus (index.mjs:183:1)
    at web.js:5:23
    at web.js:359:3
    at web.js:361:12
```

where line 183 is `chrome.runtime.onMessage.addListener(handleRequest);`.

I stumbled upon this blog, [Accessing website's window object in Chrome extension](https://kpracuk.dev/articles/accessing-websites-window-object-in-chrome-extension), that explains what I'm trying to do, but was hoping to use a library like this or `ext-messenger` to help simplify it a bit. Am I on the right path or is there a method for talking between ISOLATED and MAIN scripts to share page data?

**Comment by davestewart** [comment]
Hi Kyle,

It's been a while since I worked on the code, and that's not something I know about off the top of my head (but will find the time to look at! Away right now though, so will be a few weeks).

Did you try running any of the demo code?

You can either run in dev mode and modify the code, or just pop open the console and fire off some ad-lib code.

**Comment by davestewart** [comment]
Hey again @kyletaylored,

I've started a new extension project where I need to do exactly the same thing.

I didn't realise that this could / would be a requirement, but from my initial research into this I think what is needed is to use `window.postMessage()` to and from different processes.

I want to look to wrap this into Extension Bus itself, so it's as idiomatic as `const result = await bus.callTab(...)`.

From what I can tell, `postMessage()` does not support returning data, so I'll need to do something with request ids, and make the internal use of `postMessage()` "feel" like a return.

Did you make any progress yourself?
